### ISSUE TITLE
Add option for custom disk description in upload-disk

### ISSUE THREAD

**Issue by aesteve-rh** [oVirt/ovirt-imageio#118]
`ovirt-img upload-disk` command has a fixed description for uploaded disks (i.e., `Uploaded by ovirt-img`).

Add a command line option (e.g., `--description`, `-d`) to allow custom descriptions from users.

**Comment by sri-srikanth** [comment]
Hey!
I am a Computer Science student at the University of Texas at Austin taking a Virtualization course. My two groupmates and I were wondering if we could contribute to resolving this issue if it hasn't already been. Please let me know if this would be possible and we can get started.

**Comment by aesteve-rh** [comment]
Hi @sri-srikanth ,

Sure, you can go ahead and take this one. Make sure to include some test to cover the new CLI option (check other similar tests at https://github.com/oVirt/ovirt-imageio/blob/master/test/client_options_test.py).

Thank you!
