### ISSUE TITLE
Add default values for ovirt-img add_sub_command method

### ISSUE THREAD

**Issue by aesteve-rh** [oVirt/ovirt-imageio#120]
In `test/client_options_test.py` we repeat this a lot for options parse testing:
```python
    parser = _options.Parser()
    parser.add_sub_command(
        "test", "help", lambda x: None, transfer_options=False)
```
Which is actually good since
this is important interface and we want to tests to be easy to read.

However, it would be nice to change the method defaults to make it cleaner
to call this in the tests. So that doing just:
```python
    parser.add_sub_command("test")
```
This will create a command with no help description and a function that does nothing.

**Comment by sri-srikanth** [comment]
Hey!
I am a Computer Science student at the University of Texas at Austin taking a Virtualization course. My two groupmates and I were wondering if we could contribute to resolving this issue. Please let me know if this would be possible and we can get started.

**Comment by aesteve-rh** [comment]
@sri-srikanth Yes, of course you can contribute with this issue. Thanks!
