### ISSUE TITLE
Add option for custom disk alias for uploaded disk

### ISSUE THREAD

**Issue by aesteve-rh** [oVirt/ovirt-imageio#121]
ovirt-img upload-disk command assigns a fixed disk alias based on the source image name.

Add a command line option to allow adding custom disk aliases.

**Comment by nirs** [comment]
This is very useful - changing iso disk name is not supported yet, so the only way to set the name is before the upload. It should be fixed in engine but it may not be easy. Adding an option is trivial.

Adding to 4.5.2 since this should be very easy.
