### ISSUE TITLE
--config does not show that it is unable to read the config file

### ISSUE THREAD

**Issue by awels** [oVirt/ovirt-imageio#33]
I was passing a wrong directory to -c and that was causing ovirt-imageio to not start. The logs did not indicate exactly what the problem was (unable to read config file). It would be helpful to have the path and name of the file we are trying to read so people can debug when they have passed in the wrong path/config file with -c or --config

**Comment by nirs** [comment]
Thanks @awels. I think the best way to fix this is to fail if -c argument is not a directory.

If you run:

    ./ovirt-imageio -c foo

And we cannot find foo/conf.d, ovirt-imageio will exit with error:

    Cannot find "foo/conf.d"

When running as a service, this will also fail the service if someone
delete the /etc/ovirt-imageio/conf.d directory.

What do you think?

**Comment by awels** [comment]
Sounds good to me, I managed to build a container using the rpms provided in copr btw.

**Comment by nirs** [comment]
@awels awesome. So if you use upstream version, you can simplify your setup
code using the new ovirt-imageioctl command. For example you can add a ticket
using:

    ovirt-imageioctl add-ticket myticket.json

Instead of complicated curl command.

The command is documented in the admin guide, see #5.

**Comment by nirs** [comment]
> https://github.com/kubevirt/containerized-data-importer/pull/2156/files#diff-51d136650b3c84751dfbc13037cd4106fac808c42b80302e75c36c39fad293f3R43 is the command I use to put in the test image

The curl command looks correct, but using the ovirt-imageioctl is easier,
specially if you wan to manipulate tickets manually from the command line.

It will also protects you from changes in the configuration or protocol.
I don't think we will do any, but the control socket is not a public API
so we may change on every release. The ovirt-imageioctl tool and the admin
python library are public API that will never break.

BTW we started to work on a Go imageio client library which you may find
useful, see https://github.com/oVirt/ovirt-imageio/tree/master/go.
